#!/bin/sh

iface=$(ip route list 0.0.0.0/0 | sed 's/.* dev \(\w\+\).*/\1/')
ip4=$(ip address show $iface | sed -n 's/.*inet \([0-9./]\+\) .*/\1/p')
ip6=$(ip address show $iface | sed -n 's/.*inet6 \([0-9a-f:/]\+\) .*/\1/p')

echo "$iface ($ip4)"
echo "$iface ($ip4)"

exit 0
